import '../models/recipe.dart';

List<Recipe> sampleRecipes = [
  Recipe(
    id: '1',
    title: "Pancakes",
    imageUrl: "https://www.attainable-sustainable.net/wp-content/uploads/2024/01/pancakes-1.jpg",
    category: "Breakfast",
    rating: 4.5,
    time: 20,
    ingredients: [
      "1 cup flour",
      "1 tbsp sugar",
      "1 tsp baking powder",
      "1/2 tsp salt",
      "1 cup milk",
      "1 egg",
      "2 tbsp butter, melted",
    ],
    instructions: [
      "In a bowl, mix flour, sugar, baking powder, and salt.",
      "In another bowl, whisk milk, egg, and melted butter.",
      "Combine wet and dry ingredients, stir until smooth.",
      "Heat a pan and pour 1/4 cup batter.",
      "Cook until bubbles form, flip and cook other side.",
      "Serve with syrup or fruit.",
    ],
  ),
  Recipe(
    id: '2',
    title: "Burger",
    imageUrl: "https://static01.nyt.com/images/2022/06/27/dining/kc-mushroom-beef-burgers/merlin_209008674_b3fa58fa-9bb1-4cfe-a08a-40b4dda0de78-jumbo.jpg?quality=75&auto=webp",
    category: "Lunch",
    rating: 4.2,
    time: 25,
    ingredients: [
      "2 burger buns",
      "200g beef patty",
      "1 slice cheese",
      "Lettuce",
      "Tomato",
      "Onion",
      "Ketchup & mayo",
    ],
    instructions: [
      "Season and cook beef patty until done.",
      "Toast burger buns lightly.",
      "Assemble with lettuce, tomato, onion, patty, and cheese.",
      "Add ketchup and mayo.",
      "Serve hot with fries.",
    ],
  ),
  Recipe(
    id: '3',
    title: "Steak",
    imageUrl: "https://i.pinimg.com/1200x/e8/06/a6/e806a6ffcdeaab7a6bd40d580b587499.jpg",
    category: "Dinner",
    rating: 4.8,
    time: 40,
    ingredients: [
      "1 steak (300g)",
      "2 cloves garlic",
      "1 sprig rosemary",
      "Salt & pepper",
      "2 tbsp butter",
    ],
    instructions: [
      "Season steak with salt and pepper.",
      "Heat pan and sear steak each side 3-4 minutes.",
      "Add butter, garlic, and rosemary, baste steak.",
      "Rest steak for 5 minutes.",
      "Slice and serve.",
    ],
  ),
  Recipe(
    id: '4',
    title: "Chocolate Cake",
    imageUrl: "https://www.lifeloveandsugar.com/wp-content/uploads/2014/08/Best-Moist-Chocolate-Cake1-1.jpg",
    category: "Dessert",
    rating: 4.9,
    time: 50,
    ingredients: [
      "1 cup flour",
      "1 cup sugar",
      "1/2 cup cocoa powder",
      "1 tsp baking powder",
      "1/2 cup milk",
      "2 eggs",
      "1/2 cup butter",
    ],
    instructions: [
      "Preheat oven to 180°C (350°F).",
      "Mix flour, sugar, cocoa, and baking powder.",
      "Add milk, eggs, and butter, whisk until smooth.",
      "Pour into greased cake pan.",
      "Bake 30–35 minutes.",
      "Cool, frost if desired.",
    ],
  ),
  Recipe(
    id: '5',
    title: "Omelette",
    imageUrl: "https://thelaughingcow-sea.com/wp-content/uploads/2023/08/shutterstock_304454942.webp",
    category: "Breakfast",
    rating: 4.0,
    time: 12,
    ingredients: [
      "2 eggs",
      "2 tbsp milk",
      "Salt & pepper",
      "1 tbsp butter",
      "Cheese & veggies (optional)",
    ],
    instructions: [
      "Whisk eggs with milk, salt, and pepper.",
      "Heat butter in pan.",
      "Pour egg mixture, cook until set.",
      "Add cheese or veggies if desired.",
      "Fold and serve.",
    ],
  ),
];
